

-- public."location" definition

-- Drop table

-- DROP TABLE public."location";

CREATE TABLE public."location" (
                                   id varchar(255) NOT NULL,
                                   "attributes" jsonb NULL,
                                   geoname_id int8 NULL,
                                   location_code varchar(255) NULL,
                                   location_level varchar(255) NOT NULL,
                                   parent_id varchar(255) NULL,
	CONSTRAINT location_pkey PRIMARY KEY (id),
	CONSTRAINT fkm5xl34yboc8re75qsac6svt6g FOREIGN KEY (parent_id) REFERENCES public."location"(id)
);


-- public.location_name definition

-- Drop table

-- DROP TABLE public.location_name;

CREATE TABLE public.location_name (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      locale_code varchar(255) NOT NULL,
                                      "name" varchar(255) NOT NULL,
                                      location_id varchar(255) NOT NULL,
                                      CONSTRAINT location_name_pkey PRIMARY KEY (id),
                                      CONSTRAINT fknvf4ycj6n0j4byv6umbm0nxtw FOREIGN KEY (location_id) REFERENCES public."location"(id)
);


-- public."user" definition

-- Drop table

-- DROP TABLE public."user";

CREATE TABLE public."user" (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               api_key varchar(255) NOT NULL,
                               "name" varchar(255) NOT NULL,
                               source_ip int8 NULL,
                               user_type varchar(255) NULL,
                               parent_id int8 NULL,
                               CONSTRAINT user_pkey PRIMARY KEY (id),
	CONSTRAINT fkgcpxejhb35rkb0jd79pnvnrbb FOREIGN KEY (parent_id) REFERENCES public."user"(id)
);


-- public.ip_mapping definition

-- Drop table

-- DROP TABLE public.ip_mapping;

CREATE TABLE public.ip_mapping (
                                   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   created_at timestamp NULL,
                                   deleted_at timestamp NULL,
                                   ip_notation varchar(255) NULL,
                                   notation_type varchar(255) NULL,
                                   registered_country_id varchar(255) NULL,
                                   represented_country_id varchar(255) NULL,
                                   "scope" varchar(255) NULL,
                                   updated_at timestamp NULL,
                                   valid_period timestamp NULL,
                                   location_id varchar(255) NULL,
                                   user_id int8 NULL,
	CONSTRAINT ip_mapping_pkey PRIMARY KEY (id),
	CONSTRAINT fk9q5ovff9uac3hsb05ijlwa38w FOREIGN KEY (location_id) REFERENCES public."location"(id),
	CONSTRAINT fk9ylue9blxhsjvytcpad5wtcxr FOREIGN KEY (user_id) REFERENCES public."user"(id)
);


-- public.ip_mapping_attribute definition

-- Drop table

-- DROP TABLE public.ip_mapping_attribute;

CREATE TABLE public.ip_mapping_attribute (
                                             id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                             "attributes" jsonb NOT NULL,
                                             object_name varchar(255) NULL,
                                             ip_mapping_id int8 NOT NULL,
	CONSTRAINT ip_mapping_attribute_pkey PRIMARY KEY (id),
	CONSTRAINT fkevp5mxhg8dce3ywv1a03f2hei FOREIGN KEY (ip_mapping_id) REFERENCES public.ip_mapping(id)
);


-- public.ip_span definition

-- Drop table

-- DROP TABLE public.ip_span;

CREATE TABLE public.ip_span (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                ip_lower int8 NULL,
                                ip_upper int8 NULL,
                                ip_range      int8range GENERATED ALWAYS AS (int8range(ip_lower, ip_upper, '[]')) STORED,
                                ip_mapping_id int8 NULL,
                                CONSTRAINT ip_span_pkey PRIMARY KEY (id),
                                CONSTRAINT fkhtu976kprc936rb3a4mp68yit FOREIGN KEY (ip_mapping_id) REFERENCES public.ip_mapping(id)
);



CREATE INDEX idx_ip_span_gist ON ip_span USING GIST (ip_range);




