package com.hmg.ipmap.user.dto;

import com.hmg.ipmap.common.enums.UserType;
import com.hmg.ipmap.user.UserResponseTemplateEnum;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserResponseDto {
    @Schema(description = "The user identifier generated by system", example = "100")
    private Long id;

    @Schema(description = "The parent user of the user", example = "10")
    private Long parentId;

    @Schema(description = "The user name", example = "John Doe")
    private String name;

    @Schema(description = "The source ip of the user", example = "127.0.0.1")
    private String sourceIp;

    @Schema(description = "The user type of the user", example = "SUB_CLIENT")
    private UserType userType;

    @Schema(
            description = "The api key of the user",
            example = "86ce180a-3ec1-4c8d-a4c4-faf878809a3c")
    private String apiKey;

    @Schema(description = "The response template configured for this user", example = "DEFAULT")
    private UserResponseTemplateEnum responseTemplate;
}
