package com.hmg.ipmap.location;

import com.hmg.ipmap.cache.event.CacheEntityListener;
import com.hmg.ipmap.common.CachedEntity;
import com.hmg.ipmap.common.entity.AuditableEntity;
import com.hmg.ipmap.ipmapping.IpMappingEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.Map;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * JPA entity storing a JSONB attribute block for an {@link
 * com.hmg.ipmap.ipmapping.IpMappingEntity}.
 *
 * <p>Each row corresponds to a named attribute block (e.g. POSTAL, LOCATION) of supplementary
 * metadata attached to an IP mapping. The {@code objectName} is stored as a plain string so new
 * attribute types can be added without changing the schema or enum.
 *
 * <p>Changes to this entity automatically trigger cache synchronisation via {@link
 * CacheEntityListener}.
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "ip_mapping_attribute")
@EntityListeners(CacheEntityListener.class)
public class IpMappingAttributeEntity extends AuditableEntity implements CachedEntity {

    /** Primary key, auto-generated by database identity. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The IP mapping this attribute block belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ip_mapping_id", nullable = false)
    private IpMappingEntity ipMapping;

    /** Identifies which JSON section this row represents (e.g. POSTAL, LOCATION). */
    @Column(name = "object_name")
    private String objectName;

    /** JSONB payload carrying the key-value attribute pairs for the named section. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "attributes", nullable = false, columnDefinition = "jsonb")
    private Map<String, Object> attributes;
}
