package com.hmg.ipmap.location;

import com.hmg.ipmap.cache.event.CacheEntityListener;
import com.hmg.ipmap.common.CachedEntity;
import com.hmg.ipmap.common.entity.AuditableEntity;
import com.hmg.ipmap.common.enums.Scope;
import com.hmg.ipmap.user.UserEntity;
import jakarta.persistence.*;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.List;
import java.util.Map;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.ColumnTransformer;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * JPA entity representing a geographic location node in a hierarchical tree.
 *
 * <p>Each record corresponds to a single tier in the continent → country → subdivision → city
 * hierarchy. The hierarchy is navigated via the {@link #parent} association and materialised as an
 * {@code ltree} path in {@link #pathIds} for efficient ancestor/descendant queries.
 *
 * <p>Changes to this entity automatically trigger cache synchronisation via {@link
 * CacheEntityListener}.
 */
@Entity
@Table(name = "location")
@EntityListeners(CacheEntityListener.class)
@Getter
@Setter
public class LocationEntity extends AuditableEntity implements CachedEntity {

    /** Primary key, auto-generated by database identity. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Direct parent in the location hierarchy; {@code null} for root continent entries. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    private LocationEntity parent;

    @Column(name = "location_level", nullable = false)
    private String locationLevel;

    /** ISO or service-specific code identifying this location (e.g. {@code "US"}, {@code "KR"}). */
    @Column(name = "location_code")
    private String locationCode;

    /** GeoNames database identifier; used as a stable external reference for this location. */
    @Column(name = "geoname_id")
    private Long geonameId;

    /** Free-form JSONB attributes stored with this location (e.g. {@code is_in_european_union}). */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "attributes", columnDefinition = "jsonb")
    private Map<String, Object> attributes;

    /** Access scope that governs which user tier this location is visible to. */
    @Enumerated(EnumType.STRING)
    @Column(name = "scope")
    private Scope scope;

    /** User account that owns this location record. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private UserEntity user;

    /** Localized display names for this location, one row per locale code. */
    @OneToMany(mappedBy = "location")
    private List<LocationNameEntity> names;

    /** Materialized ltree path of ancestor IDs from root to this node (e.g. {@code "1.2.5"}). */
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @ColumnTransformer(read = "path_ids::text", write = "?::ltree")
    @Column(name = "path_ids", columnDefinition = "ltree")
    private String pathIds;
}
